[package]
name = "yea_fen_uci"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# yea_fen = { path = "../yea_fen" }
yea_fen = { git = "https://github.com/mendelsshop/yea_fen" }
